/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InsightImport } from './routes/insight'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const InsightRoute = InsightImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/insight': {
      id: '/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof InsightImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insight': typeof InsightRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insight': typeof InsightRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/insight': typeof InsightRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/insight'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/insight'
  id: '__root__' | '/' | '/insight'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightRoute: typeof InsightRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightRoute: InsightRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/insight"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/insight": {
      "filePath": "insight.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
