/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotifLabImport } from './routes/notif-lab'
import { Route as InsightImport } from './routes/insight'
import { Route as AsciiImport } from './routes/ascii'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NotifLabRoute = NotifLabImport.update({
  id: '/notif-lab',
  path: '/notif-lab',
  getParentRoute: () => rootRoute,
} as any)

const InsightRoute = InsightImport.update({
  id: '/insight',
  path: '/insight',
  getParentRoute: () => rootRoute,
} as any)

const AsciiRoute = AsciiImport.update({
  id: '/ascii',
  path: '/ascii',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/ascii': {
      id: '/ascii'
      path: '/ascii'
      fullPath: '/ascii'
      preLoaderRoute: typeof AsciiImport
      parentRoute: typeof rootRoute
    }
    '/insight': {
      id: '/insight'
      path: '/insight'
      fullPath: '/insight'
      preLoaderRoute: typeof InsightImport
      parentRoute: typeof rootRoute
    }
    '/notif-lab': {
      id: '/notif-lab'
      path: '/notif-lab'
      fullPath: '/notif-lab'
      preLoaderRoute: typeof NotifLabImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascii': typeof AsciiRoute
  '/insight': typeof InsightRoute
  '/notif-lab': typeof NotifLabRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascii': typeof AsciiRoute
  '/insight': typeof InsightRoute
  '/notif-lab': typeof NotifLabRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/ascii': typeof AsciiRoute
  '/insight': typeof InsightRoute
  '/notif-lab': typeof NotifLabRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ascii' | '/insight' | '/notif-lab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ascii' | '/insight' | '/notif-lab'
  id: '__root__' | '/' | '/ascii' | '/insight' | '/notif-lab'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsciiRoute: typeof AsciiRoute
  InsightRoute: typeof InsightRoute
  NotifLabRoute: typeof NotifLabRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsciiRoute: AsciiRoute,
  InsightRoute: InsightRoute,
  NotifLabRoute: NotifLabRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/ascii",
        "/insight",
        "/notif-lab"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/ascii": {
      "filePath": "ascii.tsx"
    },
    "/insight": {
      "filePath": "insight.tsx"
    },
    "/notif-lab": {
      "filePath": "notif-lab.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
