/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IntelImport } from './routes/intel'
import { Route as GlyphImport } from './routes/glyph'
import { Route as EchoImport } from './routes/echo'
import { Route as CipherImport } from './routes/cipher'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const IntelRoute = IntelImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRoute,
} as any)

const GlyphRoute = GlyphImport.update({
  id: '/glyph',
  path: '/glyph',
  getParentRoute: () => rootRoute,
} as any)

const EchoRoute = EchoImport.update({
  id: '/echo',
  path: '/echo',
  getParentRoute: () => rootRoute,
} as any)

const CipherRoute = CipherImport.update({
  id: '/cipher',
  path: '/cipher',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cipher': {
      id: '/cipher'
      path: '/cipher'
      fullPath: '/cipher'
      preLoaderRoute: typeof CipherImport
      parentRoute: typeof rootRoute
    }
    '/echo': {
      id: '/echo'
      path: '/echo'
      fullPath: '/echo'
      preLoaderRoute: typeof EchoImport
      parentRoute: typeof rootRoute
    }
    '/glyph': {
      id: '/glyph'
      path: '/glyph'
      fullPath: '/glyph'
      preLoaderRoute: typeof GlyphImport
      parentRoute: typeof rootRoute
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cipher': typeof CipherRoute
  '/echo': typeof EchoRoute
  '/glyph': typeof GlyphRoute
  '/intel': typeof IntelRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cipher': typeof CipherRoute
  '/echo': typeof EchoRoute
  '/glyph': typeof GlyphRoute
  '/intel': typeof IntelRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cipher': typeof CipherRoute
  '/echo': typeof EchoRoute
  '/glyph': typeof GlyphRoute
  '/intel': typeof IntelRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cipher' | '/echo' | '/glyph' | '/intel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cipher' | '/echo' | '/glyph' | '/intel'
  id: '__root__' | '/' | '/cipher' | '/echo' | '/glyph' | '/intel'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CipherRoute: typeof CipherRoute
  EchoRoute: typeof EchoRoute
  GlyphRoute: typeof GlyphRoute
  IntelRoute: typeof IntelRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CipherRoute: CipherRoute,
  EchoRoute: EchoRoute,
  GlyphRoute: GlyphRoute,
  IntelRoute: IntelRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cipher",
        "/echo",
        "/glyph",
        "/intel"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cipher": {
      "filePath": "cipher.tsx"
    },
    "/echo": {
      "filePath": "echo.tsx"
    },
    "/glyph": {
      "filePath": "glyph.tsx"
    },
    "/intel": {
      "filePath": "intel.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
